### ISSUE TITLE
Suggestions for Commonwealth

### ISSUE THREAD

**Issue by BillBillBi** [SpacedOutChicken/DeCiv-Redux#51]
The Commonwealth as of now is weak, defenseless and needs something to better distinguish itself from other civilizations. Reintroducing the 5% production bonus from connected city states, allowing Great Rangers to generate more easily, providing three merchant slots for the caravan office or improving city state influence decay should be considered. Perhaps a mid to late game unique building or unit should also be considered. My last far fetched idea is the 'Skilled Migrant Program': which allows players to select which great person is gifted by city states after finishing the liberty policy tree. Cheers.

**Comment by HaneulCheong** [comment]
@SpacedOutChicken Wasn't this already addressed in 1aa0a2ce92feb0d8912876a5bdd926c6eae46d09?

**Comment by SpacedOutChicken** [comment]
Partially addressed, at least. I am considering adding another unique to the Commonwealth to improve their relations with city-states. Possibly raising the minimum Influence point.
